"""Policy generator — writes CLAUDE.md and repo_policy.yaml for a target repository."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from .classifier import ClassifiedRepo, RiskLevel
from .scanner import scan_repo

# ── CLAUDE.md template (existing) ───────────────────────────────────────────

_CLAUDE_TEMPLATE = """\
# CLAUDE.md — Agent Policy

> Generated by AIAlchemy Repo Governor. Review and customize before committing.

## Project Overview

**Repository:** `{name}`
**Risk Level:** {risk_level}

## Allowed Operations

- Read any source file.
- Run linters, formatters, and the test suite.
- Create new files and directories.
- Edit existing source files.

## Forbidden Operations

- Do **not** delete files without explicit user confirmation.
- Do **not** commit or push changes automatically.
- Do **not** read, print, or expose the contents of `.env`, credential, or secret files.
- Do **not** install packages globally or modify system configuration.
- Do **not** run destructive commands (`rm -rf`, `git reset --hard`, `DROP TABLE`, etc.).

## Safe Directories

All directories in this repository are in-scope for the agent unless listed below.

### Out-of-scope (do not touch)

- `.git/`
- Any directory named `secrets/`, `credentials/`, or `private/`

## Environment

- **Language(s):** {languages}
- **Build tool:** {build_tool}

## Notes

{notes}
"""

# ── YAML policy constants ────────────────────────────────────────────────────

DEFAULT_BLOCKED_PATHS: list[str] = [
    ".env",
    ".env.*",
    ".venv/",
    "venv/",
    "env/",
    "__pycache__/",
    "*.db",
    "*.sqlite",
    "*.log",
    "secrets/",
    "private/",
    "credentials/",
]

_SECRET_BLOCKED_PATTERNS: list[str] = [
    ".env",
    "*.pem",
    "id_rsa",
    "id_ed25519",
    "credentials.json",
    "secrets.json",
    "token.json",
]

_SKIP_IN_ALLOWED = frozenset({
    ".git", ".venv", "venv", "env", "node_modules",
    "__pycache__", ".mypy_cache", ".pytest_cache",
    "dist", "build", "secrets", "private", "credentials",
})

_SRC_DIRS = frozenset({"src", "lib", "app", "api", "core", "pkg", "source"})
_TEST_DIRS = frozenset({"tests", "test", "spec", "__tests__"})
_DOC_DIRS = frozenset({"docs", "doc", "documentation", "examples", "notebooks"})


# ── helpers ──────────────────────────────────────────────────────────────────

def _available_dirs(repo_path: Path) -> list[str]:
    """Non-blocked top-level directories, sorted."""
    try:
        return sorted(
            d.name
            for d in repo_path.iterdir()
            if d.is_dir() and d.name not in _SKIP_IN_ALLOWED
        )
    except (PermissionError, OSError):
        return []


def _allowed_edit_paths(repo_path: Path, risk_level: RiskLevel) -> list[str]:
    available = _available_dirs(repo_path)

    if risk_level == RiskLevel.HIGH:
        found = [d for d in available if d in _SRC_DIRS | _TEST_DIRS]
        return [f"{d}/" for d in found] or ["src/"]

    if risk_level == RiskLevel.MEDIUM:
        found = [d for d in available if d in _SRC_DIRS | _TEST_DIRS | _DOC_DIRS]
        return [f"{d}/" for d in found] or ["src/", "tests/"]

    # LOW — allow everything that is not blocked
    return [f"{d}/" for d in available] or ["./"]


def _agent_permissions(risk_level: RiskLevel) -> dict[str, str]:
    if risk_level == RiskLevel.HIGH:
        return {
            "read": "allowed",
            "edit": "restricted",
            "shell": "restricted",
            "network": "denied_by_default",
        }
    if risk_level == RiskLevel.MEDIUM:
        return {
            "read": "allowed",
            "edit": "allowed_in_src_and_tests",
            "shell": "restricted",
            "network": "denied_by_default",
        }
    return {
        "read": "allowed",
        "edit": "allowed",
        "shell": "restricted",
        "network": "denied_by_default",
    }


def _required_checks(risk_level: RiskLevel, has_tests_dir: bool) -> list[str]:
    if risk_level == RiskLevel.HIGH:
        return ["run_tests", "security_scan", "human_review"]
    if risk_level == RiskLevel.MEDIUM:
        return ["run_tests", "lint_check"]
    return ["run_tests"] if has_tests_dir else ["lint_check"]


# ── YAML policy public API ───────────────────────────────────────────────────

def generate_repo_policy(cr: ClassifiedRepo) -> dict[str, Any]:
    """Return the structured policy dict for a ClassifiedRepo.

    The returned dict maps 1-to-1 onto the repo_policy.yaml schema.
    No filesystem access — pure data transformation.
    """
    repo = cr.repo
    risk = cr.risk_level

    commit_tests = (
        True
        if risk in (RiskLevel.HIGH, RiskLevel.MEDIUM)
        else repo.has_tests_dir
    )

    notes = cr.risk_reasons[:10] if cr.risk_reasons else ["No significant risks detected."]

    return {
        "repo_name": repo.name,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "risk_level": risk.value,
        "readiness_score": cr.readiness_score,
        "allowed_edit_paths": _allowed_edit_paths(repo.path, risk),
        "blocked_paths": DEFAULT_BLOCKED_PATHS,
        "required_checks": _required_checks(risk, repo.has_tests_dir),
        "agent_permissions": _agent_permissions(risk),
        "commit_requires_tests": commit_tests,
        "push_requires_human_approval": True,
        "secret_handling": {
            "scan_before_commit": True,
            "blocked_patterns": _SECRET_BLOCKED_PATTERNS,
            "alert_on_detection": True,
        },
        "report_paths": ["repo_governor_report_*.md"],
        "notes": notes,
    }


def write_repo_policy(
    repo_path: Path,
    cr: ClassifiedRepo,
    overwrite: bool = False,
) -> Path:
    """Write repo_policy.yaml to repo_path.

    Raises FileExistsError if repo_policy.yaml already exists and overwrite is False.
    """
    target = repo_path / "repo_policy.yaml"
    if target.exists() and not overwrite:
        raise FileExistsError(
            f"{target} already exists. Pass --overwrite to replace it."
        )

    policy = generate_repo_policy(cr)

    header = (
        "# AIAlchemy Repo Governor — Machine-Readable Policy\n"
        "# Generated by: repo-governor policy-init\n"
        "# Review and customize before committing.\n"
        "#\n"
    )
    body = yaml.dump(
        policy,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        indent=2,
    )

    target.write_text(header + body, encoding="utf-8")
    return target


# ── CLAUDE.md public API (unchanged) ────────────────────────────────────────

def generate_policy(repo_path: Path, risk_level: str = "UNKNOWN") -> str:
    """Return CLAUDE.md content for the given repo path."""
    repo = scan_repo(repo_path)

    languages = ", ".join(repo.languages) if repo.languages else "Unknown"

    if repo.has_pyproject:
        build_tool = "pyproject.toml (Python)"
    elif repo.has_requirements_txt:
        build_tool = "requirements.txt (Python)"
    else:
        build_tool = "Not detected"

    notes_lines: list[str] = []
    if repo.has_env_files:
        notes_lines.append(
            f"- **WARNING:** Sensitive files detected: {', '.join(repo.env_file_paths)}. "
            "Ensure these are in .gitignore and rotate any exposed credentials."
        )
    if not repo.has_gitignore:
        notes_lines.append("- No .gitignore found. Add one before agent use.")
    if not notes_lines:
        notes_lines.append("- No special notes.")

    return _CLAUDE_TEMPLATE.format(
        name=repo.name,
        risk_level=risk_level,
        languages=languages,
        build_tool=build_tool,
        notes="\n".join(notes_lines),
    )


def write_policy(repo_path: Path, risk_level: str = "UNKNOWN", overwrite: bool = False) -> Path:
    """Write CLAUDE.md to repo_path. Raises FileExistsError if it exists and overwrite is False."""
    target = repo_path / "CLAUDE.md"
    if target.exists() and not overwrite:
        raise FileExistsError(
            f"{target} already exists. Pass --overwrite to replace it."
        )
    content = generate_policy(repo_path, risk_level)
    target.write_text(content, encoding="utf-8")
    return target
