"""Markdown report generator — produces up to three report files per scan run."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .classifier import ClassifiedRepo, RiskLevel

_RISK_EMOJI = {
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🔴",
}

_HEADER_WARNING = (
    "> **Security notice:** This report may contain local file paths and repository "
    "weaknesses. Review before committing or sharing."
)


def _badge(level: RiskLevel) -> str:
    return f"{_RISK_EMOJI[level]} {level.value}"


def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


# ── Report 1: AI_REPO_GOVERNANCE_REPORT ──────────────────────────────────────

def generate_report(classified: list[ClassifiedRepo], root_path: Path) -> str:
    """Return the main governance Markdown report string."""
    total = len(classified)
    high = sum(1 for r in classified if r.risk_level == RiskLevel.HIGH)
    medium = sum(1 for r in classified if r.risk_level == RiskLevel.MEDIUM)
    low = sum(1 for r in classified if r.risk_level == RiskLevel.LOW)
    ready = sum(1 for r in classified if r.agent_ready)

    lines: list[str] = [
        "# AIAlchemy Repo Governor — Governance Report",
        "",
        _HEADER_WARNING,
        "",
        f"**Generated:** {_now()}  ",
        f"**Root path:** `{root_path}`  ",
        f"**Repos scanned:** {total}",
        "",
        "## Executive Summary",
        "",
        f"Scanned **{total}** repositories. "
        f"**{high}** HIGH-risk, **{medium}** MEDIUM-risk, **{low}** LOW-risk. "
        f"**{ready}** agent-ready.",
        "",
        "## Summary",
        "",
        "| Risk Level | Count |",
        "|------------|-------|",
        f"| 🔴 HIGH | {high} |",
        f"| 🟡 MEDIUM | {medium} |",
        f"| 🟢 LOW | {low} |",
        f"| ✅ Agent-Ready | {ready} |",
        "",
        "## Repository Overview",
        "",
        "| Repo | Risk | Score | Git | .gitignore | README | CLAUDE.md | AGENTS.md | Files |",
        "|------|------|-------|-----|-----------|--------|-----------|-----------|-------|",
    ]

    for cr in classified:
        r = cr.repo
        y, n = "✅", "❌"
        lines.append(
            f"| `{r.name}` "
            f"| {_badge(cr.risk_level)} "
            f"| {cr.readiness_score}/100 "
            f"| {y if r.is_git_repo else n} "
            f"| {y if r.has_gitignore else n} "
            f"| {y if r.has_readme else n} "
            f"| {y if r.has_claude_md else n} "
            f"| {y if r.has_agents_md else n} "
            f"| {r.file_count} |"
        )

    lines += ["", "## Detailed Findings", ""]

    for cr in classified:
        r = cr.repo
        lines += [
            f"### `{r.name}`",
            "",
            f"- **Path:** `{r.path}`",
            f"- **Risk:** {_badge(cr.risk_level)}",
            f"- **Readiness Score:** {cr.readiness_score}/100",
            f"- **Agent Ready:** {'Yes ✅' if cr.agent_ready else 'No ❌'}",
            f"- **Files:** {r.file_count}",
            f"- **Languages:** {', '.join(r.languages) if r.languages else '—'}",
            f"- **Last Modified:** {r.last_modified.strftime('%Y-%m-%d')}",
            "",
        ]

        if cr.blocking_issues:
            lines += ["**🚫 Blocking Issues:**", ""]
            lines += [f"- {issue}" for issue in cr.blocking_issues]
            lines.append("")

        if cr.risk_factors:
            lines += ["**Risk Factors:**", ""]
            lines += [f"- {f}" for f in cr.risk_factors]
            lines.append("")

        if cr.recommendations:
            lines += ["**Recommended Actions:**", ""]
            lines += [f"- {rec}" for rec in cr.recommendations]
            lines.append("")

        api_terms = getattr(cr.repo, "api_terms_found", [])
        if api_terms:
            lines += [f"**API/Operational Terms Detected:** {', '.join(api_terms)}", ""]

    lines += [
        "---",
        "",
        "> *Generated by "
        "[AIAlchemy Repo Governor](https://github.com/driaialchemy/AIAlchemy-Repo-Governor). "
        "Do not commit this report without reviewing for sensitive paths.*",
    ]

    return "\n".join(lines)


# ── Report 2: agent_readiness_report ─────────────────────────────────────────

def generate_agent_readiness_report(classified: list[ClassifiedRepo], root_path: Path) -> str:
    """Return an agent-readiness-focused Markdown report string."""
    ready = [cr for cr in classified if cr.agent_ready]
    minor = [
        cr for cr in classified
        if not cr.agent_ready and cr.risk_level == RiskLevel.LOW
    ]
    blocked = [cr for cr in classified if cr.risk_level != RiskLevel.LOW]

    lines: list[str] = [
        "# Agent Readiness Report",
        "",
        _HEADER_WARNING,
        "",
        f"**Generated:** {_now()}  ",
        f"**Root path:** `{root_path}`",
        "",
        f"**Ready now:** {len(ready)}  |  "
        f"**Ready after minor cleanup:** {len(minor)}  |  "
        f"**Blocked:** {len(blocked)}",
        "",
    ]

    if ready:
        lines += ["## ✅ Ready Now", ""]
        for cr in ready:
            lines.append(f"- `{cr.repo.name}` — score {cr.readiness_score}/100")
        lines.append("")

    if minor:
        lines += ["## 🟡 Ready After Minor Cleanup", ""]
        for cr in minor:
            lines.append(f"### `{cr.repo.name}`")
            lines.append("")
            for rec in cr.recommendations[:3]:
                lines.append(f"- {rec}")
            lines.append("")

    if blocked:
        lines += ["## 🔴 Blocked", ""]
        for cr in blocked:
            lines.append(f"### `{cr.repo.name}` — {cr.risk_level.value}")
            lines.append("")
            for issue in cr.blocking_issues:
                lines.append(f"- 🚫 {issue}")
            for factor in cr.risk_factors[:3]:
                lines.append(f"- ⚠  {factor}")
            lines.append("")

    lines += [
        "## Required Checks Before Claude Code / Codex Use",
        "",
        "1. Repo must be a git repository.",
        "2. `.gitignore` must be present.",
        "3. No `.env` or credential files exposed.",
        "4. `CLAUDE.md` must be present.",
        "5. Risk level must be LOW.",
        "",
        "---",
        "> *Generated by AIAlchemy Repo Governor*",
    ]

    return "\n".join(lines)


# ── Report 3: cleanup_recommendations ────────────────────────────────────────

def generate_cleanup_report(classified: list[ClassifiedRepo], root_path: Path) -> str:
    """Return a cleanup-recommendations Markdown report string."""
    lines: list[str] = [
        "# Cleanup Recommendations",
        "",
        _HEADER_WARNING,
        "",
        f"**Generated:** {_now()}  ",
        f"**Root path:** `{root_path}`",
        "",
        "> **Warning:** Review all suggested commands before running. "
        "No commands are executed automatically — this report is read-only advice.",
        "",
    ]

    needs_work = [cr for cr in classified if not cr.agent_ready or cr.risk_level != RiskLevel.LOW]

    if not needs_work:
        lines += ["All scanned repositories are agent-ready. No cleanup required.", ""]
    else:
        for cr in needs_work:
            r = cr.repo
            lines += [f"## `{r.name}`", "", f"**Risk:** {_badge(cr.risk_level)}  ", ""]

            if cr.blocking_issues:
                lines += ["**Blocking issues to resolve first:**", ""]
                for issue in cr.blocking_issues:
                    lines.append(f"- {issue}")
                lines.append("")

            if cr.recommendations:
                lines += ["**Suggested cleanup steps:**", ""]
                for rec in cr.recommendations:
                    lines.append(f"- {rec}")
                lines.append("")

            # safe command hints
            hints: list[str] = []
            if not r.has_gitignore:
                hints.append("# Create .gitignore\necho '*.pyc\\n.env\\n__pycache__/' > .gitignore")
            if not r.has_readme:
                hints.append("# Create README\necho '# My Project' > README.md")
            if r.has_env_files:
                hints.append(
                    "# Check secret files are in .gitignore — DO NOT delete without reviewing\n"
                    "# git check-ignore -v .env"
                )
            if hints:
                lines += ["**Sample commands (review before running):**", "", "```bash"]
                lines += hints
                lines += ["```", ""]

    lines += [
        "---",
        "> *Generated by AIAlchemy Repo Governor. "
        "Do not commit this report without reviewing for sensitive paths.*",
    ]

    return "\n".join(lines)


# ── Public write API ──────────────────────────────────────────────────────────

def write_report(
    classified: list[ClassifiedRepo],
    root_path: Path,
    output_path: Path | None = None,
) -> Path:
    """Write the main governance report. Returns the output path."""
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = Path.cwd() / f"repo_governor_report_{timestamp}.md"
    content = generate_report(classified, root_path)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def write_all_reports(
    classified: list[ClassifiedRepo],
    root_path: Path,
    output_dir: Path,
) -> list[Path]:
    """Write all three reports to output_dir. Creates the directory if needed."""
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for name, fn in [
        ("AI_REPO_GOVERNANCE_REPORT.md", generate_report),
        ("agent_readiness_report.md", generate_agent_readiness_report),
        ("cleanup_recommendations.md", generate_cleanup_report),
    ]:
        p = output_dir / name
        p.write_text(fn(classified, root_path), encoding="utf-8")
        paths.append(p)
    return paths
